server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/auth/**
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/api/products/**
        - id: inventory-service
          uri: lb://inventory-service
          predicates:
            - Path=/api/inventory/**
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/api/orders/**

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

jwt:
  public-key: "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAvIDJcMm+p1B+0R8NTeIJN2lGQADP0lRWz5eZ2e9SBauOhGba27datc5Z52iqqOppfuThavTxd/Q40qeQXlCJ6RnTLdgnP9N1iCewi04f7s2iXKHP+opWfdmDjnn9WHUxKvcYhlYgfODyvE3XGJoLn44TDFD4jv/QRwzRWOE4sg7Ap5CCFIn2wrFIxmOZyjUmznITtvnAddMh7m1zK0sNrDUTMpstaZgHBsDvOh3dZDYv84fd4IpEnwGrZj6dHy4srLUXetazDylSEnbtpQts5EOpUu4K3Uv4pfPHau13pMJ9dvUnBuqrZIOmqAOXDP4IYMYgCrynEFor1XkvMPgb8QIDAQAB"
